In [1]:
# Numpy Task

In [2]:

import numpy

In [3]:
# Q1: Arrays

In [4]:
def arrays(arr):
    arr1 = numpy.array(arr, dtype = float)
    arr2 = numpy.array(arr[::-1], dtype = float)
    return arr2

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

    

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [5]:
# Q2 : Shape and Reshape

In [6]:
def array1(arr):
    arr1 = numpy.array(arr,dtype =int)
    arr2= arr1.reshape(3,3)
    return arr2

arr = input().strip().split(' ')
result = array1(arr)
print(result)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#Q3.Transpose and Flatten

In [ ]:
def array1(arr):
    arr1 = numpy.array(arr,dtype =int)
    arr2= arr1.transpose() 
    return arr2

arr = input().strip().split(' ')
result = array1(arr)
print(result)

In [ ]:
#Q4.Concatenate

In [ ]:
X, Y, Z = map(int, input().split())
array = numpy.array([input().split() for i in range(X+Y)], int)

print(array)

In [ ]:
#Q5. Zeros and Ones

In [ ]:
def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = numpy.zeros(arr1, dtype = int)
    arr3 = numpy.ones(arr1, dtype = int)
    return arr2, arr3

arr = input().strip().split(' ')
arr2, arr3 = arrays(arr)

print(arr2)
print(arr3)

In [ ]:
#Q6. Eye and Identity

In [ ]:
numpy.set_printoptions(sign=' ')

N, M = map(int, input().split())
eye = numpy.eye(N, M)
print(eye)



In [ ]:
#Q7. Array Mathematics

In [ ]:
def arrays(arr, arr1, arr2):
    arr = numpy.array(arr, dtype = int)
    arr1 = numpy.array([arr1], dtype = int)
    arr2 = numpy.array([arr2], dtype = int)

    add = numpy.add(arr1,arr2)
    sub = numpy.subtract(arr1, arr2)
    mul = numpy.multiply(arr1, arr2)
    div = numpy.floor_divide(arr1, arr2)
    mod = numpy.mod(arr1, arr2)
    power = numpy.power(arr1, arr2)
    return add,sub,mul,div,mod,power

arr = input().strip().split(' ')

arr1 = input().strip().split(' ')
arr2 = input().strip().split(' ')
add,sub,mul,div,mod,power = arrays(arr, arr1, arr2)
print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(power)

In [ ]:
#Q8 Floor Ceil and Rint

In [ ]:

numpy.set_printoptions(sign=' ')
def arrays(arr):
    arr1 = numpy.array(arr, dtype = float)

    floor = numpy.floor(arr1)
    ceil = numpy.ceil(arr1)
    rint = numpy.rint(arr1)

    return floor, ceil, rint    
arr = input().strip().split(' ')
floor, ceil, rint = arrays(arr)
print(floor)
print(ceil)
print(rint)

In [ ]:
#Q9 . Sum and Product

In [ ]:
N, M = map(int, input().split())

array = numpy.array([input().split() for i in range(N)], int)

print(numpy.prod(numpy.sum(array, axis = 0), axis = None))


In [ ]:
# Q10. Min Max

In [ ]:
N, M = map(int, input().split())

A = numpy.array([input().split() for i in range(N)],dtype = int)
print(numpy.max(numpy.min(A, axis=1), axis=0))